"""
One-off script — loads an original, hand-authored diagnostic quiz question
bank for every English Topic (Classes 1-5, src/db/curriculum_seed.py) into
the `questions` table, WITHOUT any LLM call. NOT run at app startup.

Why this exists: the existing English question bank was generated by Gemini
grounded in tiny placeholder chunk content (see authored_content_english.py
for the real-content fix), so questions drifted from the actual NCERT
syllabus. This script authors questions directly — at least 8 per topic,
following the exact skill-kind style scripts/generate_questions.py's prompt
defines (PHONICS/VOCAB/READING/GRAMMAR/SENTENCE), grounded in the chapters
authored_content_english.py just loaded. Every question is validated with
the same checks scripts/generate_template_questions.py applies before an LLM
row would reach the DB.

Image fields are intentionally left empty throughout: composing a full set
of 4 concrete, depictable options that are ALL exact members of
src/ai/quiz_asset_vocabulary.py's ALL_ASSET_KEYS turned out to be a poor,
forced fit for these particular English question sets (grammar/sentence
options especially), so per that vocabulary's own rule ("leave empty rather
than invent"), none are set here.

Scoped strictly to subject="English" — does not touch any other subject's
rows.

Usage (from backend/):
    uv run python scripts/authored_questions_english.py --dry-run
    uv run python scripts/authored_questions_english.py
"""

import argparse
import asyncio
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from sqlmodel import select, update

from src.ai.quiz_asset_vocabulary import ALL_ASSET_KEYS
from src.core.database import AsyncSessionFactory
from src.models.quiz import Question, Topic

GENERATION_SOURCE = "authored:claude:v1"


def _q(text: str, options: list[str], correct: int, explanation: str) -> dict:
    return {
        "question_text": text,
        "options": options,
        "correct_option_index": correct,
        "explanation": explanation,
        "image_asset_key": None,
        "image_emoji": None,
        "option_asset_keys": None,
        "option_emojis": None,
    }


# ── Question bank, keyed by Topic.code ──────────────────────────────────────

QUESTIONS: dict[str, list[dict]] = {

    # ── Class 1 ──────────────────────────────────────────────────────────
    "EN1_PHONICS": [
        _q("Which letter makes the sound /k/ at the start of the word 'cat'?",
           ["c", "b", "s", "m"], 0, "The letter c makes the /k/ sound, like at the start of cat."),
        _q("Which word rhymes with 'hat'?",
           ["cat", "dog", "sun", "pen"], 0, "Cat and hat both end in the same '-at' sound."),
        _q("What sound does the letter 'b' make?",
           ["/b/ like in ball", "/s/ like in sun", "/m/ like in mat", "/k/ like in cat"], 0,
           "The letter b makes the /b/ sound, like at the start of ball."),
        _q("Blend the sounds /h/, /a/, /t/. What word do they make?",
           ["hat", "cat", "hot", "sat"], 0, "Blending /h/, /a/, /t/ one after another makes the word hat."),
        _q("Which word does NOT rhyme with 'dog'?",
           ["sun", "log", "fog", "jog"], 0, "Dog rhymes with log, fog, and jog, but not with sun."),
        _q("Which letter has the short vowel sound heard in 'apple'?",
           ["a", "e", "i", "o"], 0, "The letter a makes the short vowel sound heard at the start of apple."),
        _q("Change the 'b' in 'big' to a 'p'. What is the new word?",
           ["pig", "bag", "pin", "big"], 0, "Changing the first sound of big from /b/ to /p/ makes the word pig."),
        _q("Which two words belong to the same '-an' word family?",
           ["can and fan", "cat and dog", "sun and pen", "big and small"], 0,
           "Can and fan both end in the '-an' sound, so they belong to the same word family."),
    ],
    "EN1_VOCAB": [
        _q("Which word names a family member?",
           ["mother", "ball", "red", "jump"], 0, "Mother is a naming word for a person in our family."),
        _q("Which word names an animal?",
           ["dog", "book", "blue", "run"], 0, "Dog is a naming word for an animal."),
        _q("What colour is the sun?",
           ["yellow", "blue", "black", "purple"], 0, "The sun is usually described as yellow."),
        _q("Which of these is a number word?",
           ["five", "cat", "big", "jump"], 0, "Five is one of the counting words."),
        _q("Which word names a body part?",
           ["hand", "ball", "sun", "cup"], 0, "Hand is a naming word for a part of our body."),
        _q("Which word names something we eat?",
           ["rice", "chair", "moon", "dog"], 0, "Rice is a naming word for a food we eat."),
        _q("Which word names a colour?",
           ["green", "sit", "ten", "bag"], 0, "Green is a naming word for a colour."),
        _q("Which of these words names a thing we use every day, not an animal or a person?",
           ["book", "cat", "brother", "cow"], 0, "Book names an everyday object, unlike cat, brother, or cow."),
    ],
    "EN1_READING": [
        _q("The little red hen found some seeds. She asked, 'Who will help me plant these seeds?' "
           "No one said yes. Who helped the little red hen plant the seeds?",
           ["No one helped her", "The dog helped her", "The cat helped her", "The duck helped her"], 0,
           "The dog, cat, and duck all said 'Not I,' so no one helped her plant the seeds."),
        _q("The dog, the cat, and the duck did not help the hen. So the hen planted the seeds all by herself. "
           "Why did the hen plant the seeds by herself?",
           ["Because no one would help her", "Because she liked being alone",
            "Because the seeds were heavy", "Because it was raining"], 0,
           "None of the other animals agreed to help her, so she did it herself."),
        _q("When the bread was ready, the hen asked who would help her eat it. The dog, the cat, and the duck "
           "all said, 'I will!' What did the hen do when everyone wanted to eat the bread?",
           ["She ate it herself", "She shared it with everyone", "She threw it away", "She baked more bread"], 0,
           "Since no one helped her make the bread, the hen decided to eat it herself."),
        _q("'I have ten little fingers. They all belong to me.' How many fingers does the poem say the child has?",
           ["ten", "five", "two", "twenty"], 0, "The poem says 'ten little fingers'."),
        _q("'I wake up. I brush my teeth. I go to school.' What does the child do first?",
           ["wake up", "brush teeth", "go to school", "eat food"], 0, "Waking up is listed first in the sentence."),
        _q("The little red hen worked hard. She planted, cut, and baked all by herself. "
           "What lesson does this story teach?",
           ["Hard work is rewarded", "Animals cannot talk", "Bread is tasty", "Farms are big"], 0,
           "The hen worked hard alone and got to enjoy the bread she made, showing hard work is rewarded."),
        _q("'My bag is red. My ball is blue.' What colour is the ball in this sentence?",
           ["blue", "red", "green", "yellow"], 0, "The sentence says 'My ball is blue.'"),
        _q("'I go to school. I play with my friends. I come home happy.' Where does the child play with friends?",
           ["at school", "at home", "at the park", "at the shop"], 0,
           "The sentence order shows playing with friends happens at school."),
    ],
    "EN1_GRAMMAR": [
        _q("Which word in this sentence is a naming word (noun)? 'The dog runs fast.'",
           ["dog", "runs", "fast", "the"], 0, "Dog names the animal doing the action, so it is the noun."),
        _q("Choose the naming word to complete this sentence: '___ ate an apple.'",
           ["The boy", "Quickly", "Happily", "Running"], 0, "'The boy' names who ate the apple."),
        _q("Fill in the blank: 'I ___ rice every day.'",
           ["eat", "eats", "eating", "ate"], 0, "With 'I', we use the plain form 'eat' in the simple present tense."),
        _q("Fill in the blank: 'She ___ every morning.'",
           ["plays", "play", "playing", "played"], 0, "With 'she', we add -s to the verb in the simple present tense."),
        _q("Which is the correct sentence?",
           ["The bird sings.", "The bird sing.", "The bird singing.", "The bird sang."], 0,
           "Since 'bird' acts like 'it', the present tense verb needs an -s: sings."),
        _q("Fill in the blank: 'The sun ___ brightly.'",
           ["shines", "shine", "shining", "shone"], 0, "'The sun' takes an -s verb in the simple present tense: shines."),
        _q("Which word names a person, animal, place, or thing?",
           ["school", "run", "big", "quickly"], 0, "School is a naming word for a place, so it is a noun."),
        _q("Fill in the blank: 'My cat ___ milk.'",
           ["drinks", "drink", "drinking", "drank"], 0, "'My cat' takes an -s verb in the simple present tense: drinks."),
    ],

    # ── Class 2 ──────────────────────────────────────────────────────────
    "EN2_PHONICS": [
        _q("Blend the sounds /s/, /t/, /o/, /p/. What word do they make?",
           ["stop", "spot", "step", "spin"], 0, "Blending /s/, /t/, /o/, /p/ in order makes the word stop."),
        _q("Which word belongs to the '-og' family, like dog and log?",
           ["fog", "cat", "sun", "bag"], 0, "Fog ends in the same '-og' sound as dog and log."),
        _q("Which two letters together make the /sh/ sound, like in 'ship'?",
           ["sh", "ch", "th", "st"], 0, "The letters s and h together make the /sh/ sound."),
        _q("Which word starts with the /ch/ sound?",
           ["chair", "ship", "this", "sun"], 0, "Chair starts with the /ch/ digraph sound."),
        _q("Which word starts with the /th/ sound?",
           ["this", "ship", "chin", "fog"], 0, "This starts with the /th/ digraph sound."),
        _q("How many syllables (parts) does the word 'rabbit' have?",
           ["two", "one", "three", "four"], 0, "Rabbit splits into two parts: rab and bit."),
        _q("Which word belongs to the '-at' family, like cat and mat?",
           ["rat", "dog", "sun", "pen"], 0, "Rat ends in the same '-at' sound as cat and mat."),
        _q("Blend the sounds /f/, /r/, /o/, /g/. What word do they make?",
           ["frog", "fog", "flog", "from"], 0, "Blending /f/, /r/, /o/, /g/ in order makes the word frog."),
    ],
    "EN2_VOCAB": [
        _q("Which word describes size?",
           ["big", "red", "sweet", "soft"], 0, "Big describes how large something is."),
        _q("Which word describes how something feels?",
           ["hot", "blue", "tall", "five"], 0, "Hot describes a feeling of temperature."),
        _q("What is the opposite of 'big'?",
           ["small", "tall", "fast", "clean"], 0, "Small is the opposite describing word to big."),
        _q("Which word describes a colour?",
           ["yellow", "quick", "loud", "tall"], 0, "Yellow is a colour describing word."),
        _q("Which word describes how something tastes?",
           ["sweet", "soft", "big", "red"], 0, "Sweet describes a taste."),
        _q("Choose the best describing word: 'The ___ dog ran across the yard.'",
           ["big", "quickly", "jump", "school"], 0, "'Big' describes the noun 'dog', fitting before it."),
        _q("What is the opposite of 'clean'?",
           ["dirty", "big", "hot", "fast"], 0, "Dirty is the opposite describing word to clean."),
        _q("Which sentence uses a describing word correctly?",
           ["The big elephant walked slowly.", "The elephant big walked.",
            "The walked big elephant.", "Big the elephant walked."], 0,
           "Describing words like 'big' are placed before the noun they describe."),
    ],
    "EN2_READING": [
        _q("It began to rain. Raju looked out and smiled. He loved rainy days. How did Raju feel about the rain?",
           ["He was happy", "He was scared", "He was angry", "He was bored"], 0,
           "Raju smiled and loved rainy days, showing he was happy."),
        _q("Raju put on his yellow raincoat and red gumboots. What colour was Raju's raincoat?",
           ["yellow", "red", "blue", "green"], 0, "The passage says his raincoat was yellow."),
        _q("Raju jumped into the biggest puddle. Water splashed around his boots. What did Raju jump into?",
           ["a puddle", "a river", "a pool", "a bucket"], 0, "The passage says Raju jumped into a puddle."),
        _q("Meera watched from the doorway, giggling at the splashing water. Who is Meera?",
           ["Raju's sister", "Raju's mother", "Raju's teacher", "Raju's friend"], 0,
           "The passage describes Meera as Raju's little sister."),
        _q("Their mother called them inside for warm milk and biscuits. What did their mother give them?",
           ["warm milk and biscuits", "tea and cake", "juice and fruit", "soup and bread"], 0,
           "The passage says their mother gave them warm milk and biscuits."),
        _q("Raju and Meera jumped in puddle after puddle, laughing every time. How did they feel while playing?",
           ["happy", "sad", "tired", "scared"], 0, "Laughing while playing shows they felt happy."),
        _q("Dark clouds covered the sky, and soon it began to rain. What happened after the dark clouds appeared?",
           ["it began to rain", "the sun came out", "it became windy", "it got very hot"], 0,
           "The passage says it began to rain right after the clouds appeared."),
        _q("Meera ran outside too, holding her own small umbrella. What did Meera hold while going outside?",
           ["an umbrella", "a raincoat", "a bag", "a book"], 0, "The passage says Meera held her own small umbrella."),
    ],
    "EN2_GRAMMAR": [
        _q("Replace the naming word with a pronoun: 'Raju plays outside.' becomes '___ plays outside.'",
           ["He", "She", "It", "They"], 0, "Raju is a boy, so we use the pronoun he."),
        _q("Replace the naming word with a pronoun: 'Meera sings a song.' becomes '___ sings a song.'",
           ["She", "He", "It", "They"], 0, "Meera is a girl, so we use the pronoun she."),
        _q("Replace the naming word with a pronoun: 'The dog barks loudly.' becomes '___ barks loudly.'",
           ["It", "He", "She", "They"], 0, "A dog is usually replaced with the pronoun it."),
        _q("Replace the naming word with a pronoun: 'Raju and Meera play outside.' becomes '___ play outside.'",
           ["They", "He", "She", "It"], 0, "Two people together are replaced with the pronoun they."),
        _q("Choose the correct verb: 'He ___ football every day.'",
           ["plays", "play", "playing", "played"], 0, "With 'he', the present tense verb takes an -s: plays."),
        _q("Choose the correct verb: 'They ___ in the park.'",
           ["play", "plays", "playing", "played"], 0, "With 'they', the present tense verb has no -s: play."),
        _q("Which pronoun would you use in place of a girl's name?",
           ["she", "he", "it", "they"], 0, "We use she in place of a girl's name."),
        _q("Choose the correct verb: 'It ___ very fast.' (about a dog running)",
           ["runs", "run", "running", "ran"], 0, "With 'it', the present tense verb takes an -s: runs."),
    ],
    "EN2_SENTENCE": [
        _q("Which is a complete sentence?",
           ["The dog runs.", "The dog", "Runs fast", "Fast dog the"], 0,
           "'The dog runs.' has both a naming part and a telling part."),
        _q("Which sentence has both a naming part and a telling part?",
           ["Mia sings a song.", "Sings a song.", "Mia.", "A song."], 0,
           "'Mia' is the naming part and 'sings a song' is the telling part."),
        _q("Choose the correct ending punctuation: 'Is the sun bright___'",
           ["?", ".", "!", ","], 0, "A question needs a question mark at the end."),
        _q("Which words complete this sentence correctly? 'The bird ___.'",
           ["flies high", "high flies", "flies-high", "fly-high"], 0,
           "'Flies high' correctly tells us what the bird does, in the right word order."),
        _q("Which of these is NOT a complete sentence?",
           ["Runs fast.", "The cat sleeps.", "We play in the park.", "The teacher smiles."], 0,
           "'Runs fast.' has no naming part telling us who is running."),
        _q("Choose the naming part of this sentence: 'The rain falls.'",
           ["The rain", "falls", "The", "rain falls"], 0, "'The rain' names what the sentence is about."),
        _q("Choose the telling part of this sentence: 'The cat sleeps.'",
           ["sleeps", "The cat", "cat", "The"], 0, "'Sleeps' tells us what the cat does."),
        _q("Which sentence starts with a capital letter and ends correctly?",
           ["The sun is bright.", "the sun is bright", "The sun is bright", "the Sun Is Bright."], 0,
           "A complete sentence starts with a capital letter and ends with a full stop."),
    ],

    # ── Class 3 ──────────────────────────────────────────────────────────
    "EN3_VOCAB": [
        _q("Which word is a synonym for 'happy'?",
           ["glad", "sad", "angry", "tired"], 0, "Glad means almost the same as happy."),
        _q("Which word is a synonym for 'big'?",
           ["large", "small", "tiny", "short"], 0, "Large means almost the same as big."),
        _q("Which word is a synonym for 'quick'?",
           ["fast", "slow", "lazy", "calm"], 0, "Fast means almost the same as quick."),
        _q("Which word means almost the same as 'begin'?",
           ["start", "stop", "end", "finish"], 0, "Start means almost the same as begin."),
        _q("In the sentence 'The glad child smiled brightly,' what does 'glad' most likely mean?",
           ["happy", "sad", "angry", "tired"], 0, "Glad is a synonym for happy, matching the smiling child."),
        _q("Which word is a synonym for 'beautiful'?",
           ["pretty", "ugly", "dirty", "plain"], 0, "Pretty means almost the same as beautiful."),
        _q("Which word is a synonym for 'small'?",
           ["tiny", "huge", "wide", "tall"], 0, "Tiny means almost the same as small."),
        _q("Choose the sentence that uses a synonym for 'big' correctly.",
           ["The large dog barked loudly.", "The large dog small barked.",
            "Large the dog barked.", "The dog barked large."], 0,
           "'Large' is used correctly as a describing word before 'dog', like a synonym for big."),
    ],
    "EN3_READING": [
        _q("A thirsty crow found a clay pot with water at the bottom, but her beak could not reach it. "
           "Why couldn't the crow drink the water at first?",
           ["The water was too low for her beak", "The pot had no water",
            "The pot was too heavy", "The crow was not thirsty"], 0,
           "The passage says the water was too low for her beak to reach."),
        _q("The crow saw some pebbles on the ground and had a clever idea. "
           "What did the crow use to solve her problem?",
           ["pebbles", "sticks", "leaves", "sand"], 0, "The crow used pebbles to raise the water level."),
        _q("One by one, the crow dropped pebbles into the pot, and the water slowly rose. "
           "Why did the water rise in the pot?",
           ["The pebbles took up space at the bottom", "The pot had a hole",
            "More water was added", "The pot got smaller"], 0,
           "Each pebble took up space at the bottom, pushing the water level higher."),
        _q("The crow drank until she was no longer thirsty. How did the story end for the crow?",
           ["She quenched her thirst", "She gave up and left", "She broke the pot", "She found another pot"], 0,
           "The crow's clever plan worked, and she was able to drink the water."),
        _q("The crow did not give up when the water seemed out of reach. What character trait did the crow show?",
           ["cleverness and patience", "laziness", "fear", "anger"], 0,
           "The crow thought carefully and kept trying, showing cleverness and patience."),
        _q("It was a hot summer day, and the crow had not had a drop of water all day. "
           "What was the weather like in the story?",
           ["hot", "cold", "rainy", "snowy"], 0, "The passage says it was a hot summer day."),
        _q("The crow flew from tree to tree looking for water. What was the crow searching for at the start "
           "of the story?",
           ["water", "food", "a nest", "other birds"], 0, "The passage says the crow was looking for water."),
        _q("What is the moral of 'The Clever Crow'?",
           ["Thinking carefully can solve a difficult problem", "Birds should not drink water",
            "Pots are dangerous", "Crows are the fastest birds"], 0,
           "The crow solved her problem by thinking carefully, not by giving up."),
    ],
    "EN3_GRAMMAR": [
        _q("Fill in the blank: 'She ___ to school yesterday.'",
           ["walked", "walks", "walking", "will walk"], 0, "'Walked' is the simple past tense of walk."),
        _q("What is the past tense of 'go'?",
           ["went", "goed", "going", "goes"], 0, "'Went' is the irregular past tense of go."),
        _q("What is the past tense of 'eat'?",
           ["ate", "eated", "eating", "eats"], 0, "'Ate' is the irregular past tense of eat."),
        _q("Fill in the blank: 'They ___ a peacock at the zoo.'",
           ["saw", "see", "seeing", "sees"], 0, "'Saw' is the irregular past tense of see."),
        _q("Choose the correct question about something in the past.",
           ["Did she play in the park?", "Did she played in the park?",
            "Does she played in the park?", "Did she plays in the park?"], 0,
           "With 'did', we use the base form of the verb, not the -ed form."),
        _q("Choose the correct negative sentence about something in the past.",
           ["She did not play in the park.", "She did not played in the park.",
            "She does not played in the park.", "She not played in the park."], 0,
           "With 'did not', we use the base form of the verb, not the -ed form."),
        _q("What is the past tense of 'run'?",
           ["ran", "runned", "running", "runs"], 0, "'Ran' is the irregular past tense of run."),
        _q("Fill in the blank: 'He ___ an apple at lunch.'",
           ["ate", "eats", "eating", "eat"], 0, "'Ate' is the simple past tense form needed here."),
    ],
    "EN3_SENTENCE": [
        _q("Which sentence is more descriptive?",
           ["The tall, green tree stood near the house.", "The tree stood near the house.",
            "Tree house.", "The tree."], 0, "Adding 'tall, green' gives a much clearer picture of the tree."),
        _q("Choose the sentence that best describes a person.",
           ["The tall boy wore a blue shirt.", "The boy is here.", "A boy.", "Boy wore shirt."], 0,
           "This sentence uses detail words (tall, blue) to describe the boy clearly."),
        _q("Which word could describe the apple's colour in 'The ___ apple sat on the table'?",
           ["red", "tall", "loud", "fast"], 0, "Red describes colour, which fits describing an apple."),
        _q("Choose the most descriptive sentence about a market.",
           ["The busy, noisy market was full of colourful stalls.", "The market was there.",
            "Market busy.", "There was a market."], 0,
           "This sentence uses several describing words to paint a vivid picture."),
        _q("Which word describes texture (how something feels)?",
           ["shiny", "quickly", "five", "jump"], 0, "Shiny describes how a surface looks or feels."),
        _q("Choose the most descriptive version of 'The bird sat on the branch.'",
           ["The tiny, blue bird sat quietly on the branch.", "Bird sat branch.",
            "The bird the branch sat.", "Sat bird on branch the."], 0,
           "This version adds describing words (tiny, blue, quietly) for a clearer picture."),
        _q("Which sentence uses describing words correctly?",
           ["The small, round, shiny red apple sat on the table.", "The apple sat table small.",
            "Apple the sat small round.", "Table the apple sat on."], 0,
           "The describing words are placed correctly before the noun 'apple'."),
        _q("Which describing word tells us about shape?",
           ["round", "sweet", "red", "soft"], 0, "Round describes the shape of an object."),
    ],

    # ── Class 4 ──────────────────────────────────────────────────────────
    "EN4_VOCAB": [
        _q("What is the antonym (opposite) of 'big'?",
           ["small", "huge", "large", "wide"], 0, "Small is the opposite of big."),
        _q("What is a synonym for 'huge'?",
           ["enormous", "tiny", "short", "narrow"], 0, "Enormous means almost the same as huge."),
        _q("What is the antonym of 'hot'?",
           ["cold", "warm", "sunny", "dry"], 0, "Cold is the opposite of hot."),
        _q("What is a synonym for 'quiet'?",
           ["silent", "loud", "noisy", "busy"], 0, "Silent means almost the same as quiet."),
        _q("What is the antonym of 'quick'?",
           ["slow", "fast", "swift", "rapid"], 0, "Slow is the opposite of quick."),
        _q("In the sentence 'The enormous elephant walked slowly,' what does 'enormous' most likely mean?",
           ["very big", "very small", "very fast", "very loud"], 0,
           "Enormous is a synonym for very big, describing the elephant's size."),
        _q("What is a synonym for 'happy'?",
           ["joyful", "sad", "angry", "tired"], 0, "Joyful means almost the same as happy."),
        _q("What is the antonym of 'noisy'?",
           ["quiet", "loud", "busy", "fast"], 0, "Quiet is the opposite of noisy."),
    ],
    "EN4_READING": [
        _q("Gopal owned a field but no well, so he had to walk far to fetch water. "
           "Why did Gopal have to walk far every day?",
           ["He had no well of his own", "He liked walking", "He was visiting friends", "He was selling crops"], 0,
           "The passage says Gopal had no well of his own."),
        _q("Gopal saved his money for many months and finally bought the well from the trader. "
           "How did Gopal get the well?",
           ["He saved money and bought it", "He borrowed it", "He built it himself",
            "He won it in a contest"], 0, "Gopal saved money for months and then bought the well."),
        _q("The trader said he had sold the well but not the water inside it. "
           "What trick did the trader try to play on Gopal?",
           ["Charging extra for the water", "Taking back the well", "Refusing to sell the well",
            "Selling the well to someone else"], 0,
           "The trader tried to charge Gopal extra to use the water in his own well."),
        _q("Gopal went to the wise judge of the village to explain his problem. Who did Gopal ask for help?",
           ["the village judge", "his neighbour", "his family", "the trader's friend"], 0,
           "The passage says Gopal went to the wise judge of the village."),
        _q("The judge said the trader must remove his water from Gopal's well. What did the judge decide?",
           ["The trader must remove his water", "Gopal must pay extra",
            "The well belongs to the trader", "Both must share the well"], 0,
           "The judge ruled that the trader must remove his water from Gopal's well."),
        _q("What happened first in the story?",
           ["Gopal had no well of his own", "Gopal bought the well",
            "The judge gave his decision", "The trader tried to trick Gopal"], 0,
           "At the start of the story, Gopal had no well and had to walk far for water."),
        _q("What happened last in the story?",
           ["Gopal used the water freely", "Gopal bought the well",
            "The trader tried to trick him", "Gopal went to the judge"], 0,
           "After the judge's decision, Gopal was finally able to use the water freely."),
        _q("What lesson does this story teach?",
           ["Clever thinking can solve unfair tricks", "Farmers should not buy wells",
            "Judges are always wrong", "Water is not important"], 0,
           "The judge's clever decision solved the trader's unfair trick."),
    ],
    "EN4_GRAMMAR": [
        _q("Choose the sentence using an adjective correctly.",
           ["A colourful kite flew high.", "A kite colourful flew.",
            "Flew colourful kite a.", "Kite a colourful flew."], 0,
           "'Colourful' is placed correctly before the noun 'kite'."),
        _q("Fill in the blank with the future tense: 'I ___ visit my grandmother tomorrow.'",
           ["will", "am", "was", "did"], 0, "The simple future tense uses 'will' with the base verb."),
        _q("Choose the correct future tense question.",
           ["Will you visit your grandmother tomorrow?", "You will visit your grandmother tomorrow?",
            "Did you will visit?", "Will you visited?"], 0,
           "A future tense question places 'will' before the naming word."),
        _q("Choose the correct negative future sentence.",
           ["I will not go out today.", "I not will go out today.",
            "I will not went out today.", "I did not will go out."], 0,
           "The negative future tense uses 'will not' followed by the base verb."),
        _q("Fill in the blank: 'She ___ bake a cake this weekend.'",
           ["will", "is", "was", "did"], 0, "The simple future tense uses 'will' with the base verb."),
        _q("Which adjective could describe a grandmother who is caring and warm?",
           ["kind", "fast", "loud", "square"], 0, "Kind describes a caring, warm personality."),
        _q("Fill in the blank: 'They ___ travel to Delhi next month.'",
           ["will", "are", "were", "did"], 0, "The simple future tense uses 'will' with the base verb."),
        _q("Choose the sentence with two adjectives describing 'grandmother'.",
           ["A tall, kind grandmother smiled.", "A grandmother tall kind.",
            "Grandmother a tall kind smiled.", "Smiled grandmother tall kind a."], 0,
           "'Tall' and 'kind' are both placed correctly before the noun 'grandmother'."),
    ],
    "EN4_SENTENCE": [
        _q("Join using 'and': 'I like mangoes. I like bananas.'",
           ["I like mangoes and bananas.", "I like mangoes but bananas.",
            "I like mangoes because bananas.", "I like mangoes or bananas."], 0,
           "'And' correctly joins two similar liked things."),
        _q("Join using 'but': 'I wanted to go outside. It was raining.'",
           ["I wanted to go outside, but it was raining.", "I wanted to go outside, and it was raining.",
            "I wanted to go outside, because it was raining.", "I wanted to go outside, or it was raining."], 0,
           "'But' correctly shows the contrast between wanting to go out and the rain."),
        _q("Join using 'because': 'I stayed home. I was sick.'",
           ["I stayed home because I was sick.", "I stayed home but I was sick.",
            "I stayed home or I was sick.", "I stayed home, I was sick and."], 0,
           "'Because' correctly explains the reason for staying home."),
        _q("Which conjunction shows a choice between two things?",
           ["or", "and", "because", "but"], 0, "'Or' is used to show a choice between two possibilities."),
        _q("Which conjunction explains a reason for something?",
           ["because", "and", "or", "but"], 0, "'Because' connects a result to its cause."),
        _q("Which conjunction joins two similar ideas together?",
           ["and", "but", "or", "because"], 0, "'And' joins two similar ideas together."),
        _q("Join using the best conjunction: 'The sky was dark. It started to rain.'",
           ["The sky was dark, and it started to rain.", "The sky was dark, or it started to rain.",
            "The sky was dark, because it started to rain.", "The sky was dark it started to rain."], 0,
           "'And' joins these two events that happened together, in order."),
        _q("Which conjunction shows contrast between two ideas?",
           ["but", "and", "or", "because"], 0, "'But' is used to show a contrast between two ideas."),
    ],

    # ── Class 5 ──────────────────────────────────────────────────────────
    "EN5_VOCAB": [
        _q("'The parched land had not seen rain for months.' What does 'parched' most likely mean?",
           ["very dry", "very wet", "very cold", "very green"], 0,
           "The lack of rain in the sentence suggests parched means very dry."),
        _q("'The famished dog gulped down its food quickly.' What does 'famished' most likely mean?",
           ["very hungry", "very tired", "very happy", "very angry"], 0,
           "Gulping down food quickly suggests famished means very hungry."),
        _q("'She felt drowsy after lunch, her eyes kept closing.' What does 'drowsy' most likely mean?",
           ["sleepy", "excited", "hungry", "scared"], 0, "Eyes closing suggests drowsy means sleepy."),
        _q("'Although the joke was hilarious, he did not even smile.' What does 'hilarious' most likely mean?",
           ["very funny", "very sad", "very boring", "very serious"], 0,
           "The contrast with 'did not even smile' suggests hilarious means very funny."),
        _q("Which strategy helps you guess an unfamiliar word's meaning?",
           ["using clues from surrounding words", "ignoring the sentence",
            "guessing randomly", "skipping the word"], 0,
           "Context clues from surrounding words help us guess an unfamiliar word's meaning."),
        _q("'The exhausted climbers rested for hours after reaching the top.' "
           "What does 'exhausted' most likely mean?",
           ["very tired", "very excited", "very hungry", "very cold"], 0,
           "Resting for hours suggests exhausted means very tired."),
        _q("'The cracked soil crumbled underfoot in the dry heat.' This detail helps us understand which word?",
           ["parched", "drenched", "freezing", "muddy"], 0,
           "Cracked, crumbling soil in dry heat matches the meaning of parched."),
        _q("'He was ecstatic when he won the race, jumping and cheering loudly.' "
           "What does 'ecstatic' most likely mean?",
           ["extremely happy", "extremely sad", "extremely tired", "extremely angry"], 0,
           "Jumping and cheering suggest ecstatic means extremely happy."),
    ],
    "EN5_READING": [
        _q("Kamla sat under the tree every day, smiling quietly, but rarely spoke to anyone. "
           "What can we infer about Kamla?",
           ["She often thinks about something private", "She dislikes the tree",
            "She is a stranger to the village", "She never visits the tree"], 0,
           "Her quiet smiles and silence suggest she is often lost in private thought."),
        _q("The boy noticed the initials 'K + R' carved into the trunk. What might the initials suggest?",
           ["Two people who were close once carved them together", "The tree was recently planted",
            "The initials belong to strangers", "The tree is going to be cut down"], 0,
           "Carved initials of two letters usually suggest two people who were once close."),
        _q("Her eyes drifted toward the empty space beside her on the bench. "
           "What does this detail most likely suggest?",
           ["Someone who used to sit there is no longer with her", "She is looking for a new friend",
            "She wants to move the bench", "She dislikes sitting alone"], 0,
           "Looking at an empty space suggests she is remembering someone who is no longer there."),
        _q("She paused for a long moment before answering softly. What does her pause suggest about the memory?",
           ["It is an important or emotional memory", "She forgot the answer",
            "She was not listening", "She was annoyed by the question"], 0,
           "A long pause before answering softly suggests the memory is important and emotional."),
        _q("'The tree was still young and thin enough for two people to reach their arms around it together.' "
           "What can we infer from this detail?",
           ["The carving happened a long time ago, when the tree was small", "The tree was cut down recently",
            "The tree has always been huge", "Kamla planted the tree yesterday"], 0,
           "A thin, young tree tells us the carving happened long ago, before the tree grew large."),
        _q("Why might the author NOT directly say who 'R' was?",
           ["To let the reader guess and feel curious", "Because it is not important at all",
            "Because the story has no meaning", "Because R does not exist"], 0,
           "Leaving details unstated invites the reader to infer and feel curious."),
        _q("What is the overall mood of this passage?",
           ["quiet and thoughtful", "loud and cheerful", "angry and tense", "silly and playful"], 0,
           "The gentle pauses and quiet memories create a quiet, thoughtful mood."),
        _q("What can we infer about how long Kamla has been visiting the tree?",
           ["For a very long time, since she was young", "Only once",
            "For a few days", "She has never visited before"], 0,
           "The old, worn bench and old carving suggest she has visited for a very long time."),
    ],
    "EN5_GRAMMAR": [
        _q("Choose the sentence that correctly mixes past, present, and future tense.",
           ["She finished her homework, is watching TV now, and will sleep soon.",
            "She finish her homework, watch TV, will slept.",
            "She will finished homework is watch TV slept.",
            "She finished will watching sleeping."], 0,
           "This sentence correctly uses past (finished), present (is watching), and future (will sleep)."),
        _q("Which conjunction shows a result?",
           ["so", "but", "although", "when"], 0, "'So' introduces the result of an earlier action."),
        _q("Which conjunction explains a reason?",
           ["because", "so", "and", "or"], 0, "'Because' explains the reason for something."),
        _q("Fill in the blank: 'It started raining, ___ we came back inside.'",
           ["so", "but", "when", "although"], 0, "'So' shows that coming inside was a result of the rain."),
        _q("Fill in the blank: 'We came back inside ___ it started raining.'",
           ["because", "so", "or", "and"], 0, "'Because' explains the reason we came back inside."),
        _q("Which conjunction joins two actions simply, one after another?",
           ["and", "so", "because", "although"], 0, "'And' simply joins two actions together."),
        _q("Which conjunction shows contrast between two ideas?",
           ["but", "and", "so", "because"], 0, "'But' shows a contrast between two ideas."),
        _q("Choose the correct way to check tense: 'Did this already happen, is it happening now, or ___?'",
           ["will it happen later", "did it happen later", "happening it will", "later happen will"], 0,
           "'Will it happen later' correctly completes the future-tense check in proper word order."),
    ],
    "EN5_SENTENCE": [
        _q("Choose the complex sentence that explains a reason.",
           ["She was late because the bus broke down.", "She was late and the bus broke down.",
            "She was late so the bus broke down.", "She was late, the bus broke down."], 0,
           "'Because' correctly introduces the reason she was late."),
        _q("Which word introduces a surprising contrast in a complex sentence?",
           ["although", "because", "when", "if"], 0, "'Although' introduces a surprising contrast."),
        _q("Which word introduces a condition in a complex sentence?",
           ["if", "when", "because", "although"], 0, "'If' introduces a condition."),
        _q("Which word tells us about timing in a complex sentence?",
           ["when", "if", "because", "although"], 0, "'When' tells us about timing."),
        _q("Choose the sentence with the same meaning as 'She was late because the bus broke down.'",
           ["Because the bus broke down, she was late.", "She was late so the bus broke down.",
            "The bus broke down so she was late early.", "Late she was the bus broke down because."], 0,
           "Moving the clause 'because the bus broke down' to the front keeps the same meaning."),
        _q("Combine using a joining word: 'The power went out. We lit some candles.'",
           ["Because the power went out, we lit some candles.", "The power went out we lit some candles.",
            "Power the went out lit candles we.", "We lit candles power went out."], 0,
           "'Because' correctly explains the reason we lit candles."),
        _q("Choose the complex sentence using 'although' correctly.",
           ["Although it was raining heavily, the match continued.",
            "It was raining heavily the match continued.",
            "The match continued raining heavily although.",
            "Although raining continued match the heavily."], 0,
           "'Although' is placed correctly at the start to show contrast."),
        _q("Where should a comma go in this complex sentence? 'Because the bus broke down she was late'",
           ["Because the bus broke down, she was late.", "Because, the bus broke down she was late.",
            "Because the bus, broke down she was late.", "Because the bus broke, down she was late."], 0,
           "A comma is placed after the introductory clause, before the main clause."),
    ],
}


# ── Validation (adapted from scripts/generate_template_questions.py) ───────

def _validate(topic_code: str, g: dict) -> None:
    assert len(g["options"]) == 4, f"{topic_code}: expected 4 options, got {g['options']!r}"
    assert len(set(g["options"])) == 4, f"{topic_code}: duplicate option values {g['options']!r}"
    assert 0 <= g["correct_option_index"] <= 3, f"{topic_code}: bad correct_option_index"
    assert not (g["image_asset_key"] and g["image_emoji"]), (
        f"{topic_code}: image_asset_key and image_emoji both set"
    )
    assert not (g["option_asset_keys"] and g["option_emojis"]), (
        f"{topic_code}: option_asset_keys and option_emojis both set"
    )
    if g["image_asset_key"]:
        assert g["image_asset_key"] in ALL_ASSET_KEYS, (
            f"{topic_code}: unknown image_asset_key {g['image_asset_key']!r}"
        )
    if g["option_asset_keys"]:
        assert len(g["option_asset_keys"]) == 4, f"{topic_code}: option_asset_keys must have 4 entries"
        for key in g["option_asset_keys"]:
            assert key in ALL_ASSET_KEYS, f"{topic_code}: unknown option_asset_key {key!r}"
    if g["option_emojis"]:
        assert len(g["option_emojis"]) == 4, f"{topic_code}: option_emojis must have 4 entries"
    assert g["question_text"].strip(), f"{topic_code}: empty question_text"
    assert g["explanation"].strip(), f"{topic_code}: empty explanation"


async def _fetch_topics() -> dict[str, Topic]:
    async with AsyncSessionFactory() as session:
        result = await session.execute(select(Topic).where(Topic.subject == "English"))
        return {t.code: t for t in result.scalars().all()}


async def main() -> None:
    parser = argparse.ArgumentParser(description="Load authored English question bank.")
    parser.add_argument("--dry-run", action="store_true", help="Validate and print, do not write to DB.")
    args = parser.parse_args()

    topics = await _fetch_topics()
    missing_topics = [code for code in QUESTIONS if code not in topics]
    if missing_topics:
        raise SystemExit(f"Topic codes not found in DB: {missing_topics}")

    covered = set(QUESTIONS.keys())
    all_english_codes = set(topics.keys())
    uncovered = all_english_codes - covered
    if uncovered:
        print(f"[warning] English topics with NO authored questions: {sorted(uncovered)}")

    total = 0
    for topic_code, questions in QUESTIONS.items():
        for g in questions:
            _validate(topic_code, g)
        total += len(questions)
    print(f"Validated {total} authored question(s) across {len(QUESTIONS)} topic(s). OK.")

    if args.dry_run:
        for topic_code, questions in list(QUESTIONS.items())[:2]:
            print(f"\n[dry-run] {topic_code}: {len(questions)} question(s)")
            for g in questions[:2]:
                print(f"  Q: {g['question_text']}")
                print(f"  Options: {g['options']}  Correct: {g['correct_option_index']}")
        return

    generation_batch = datetime.now(timezone.utc).strftime("%Y%m%d")

    async with AsyncSessionFactory() as session:
        result = await session.execute(
            update(Question)
            .where(Question.subject == "English", Question.is_active == True)  # noqa: E712
            .values(is_active=False)
        )
        await session.commit()
        print(f"Deactivated {result.rowcount} existing active English question(s).")

    inserted = 0
    for topic_code, questions in QUESTIONS.items():
        topic = topics[topic_code]
        async with AsyncSessionFactory() as session:
            for g in questions:
                session.add(
                    Question(
                        topic_id=topic.id,
                        subject="English",
                        class_number=topic.class_number,
                        question_text=g["question_text"],
                        options=g["options"],
                        correct_option_index=g["correct_option_index"],
                        explanation=g["explanation"],
                        image_emoji=g["image_emoji"],
                        image_asset_key=g["image_asset_key"],
                        option_emojis=g["option_emojis"],
                        option_asset_keys=g["option_asset_keys"],
                        generation_source=GENERATION_SOURCE,
                        generation_batch=generation_batch,
                        module_id=None,
                        branch_name=None,
                        reviewed=False,
                        is_active=True,
                    )
                )
            await session.commit()
        print(f"  [ok] {topic_code} (C{topic.class_number}): {len(questions)} questions inserted")
        inserted += len(questions)

    print(f"\nDone. Topics covered: {len(QUESTIONS)}. Questions inserted: {inserted}.")


if __name__ == "__main__":
    asyncio.run(main())
