"""
Hand-authored NCERT-aligned chapter content — chunked/embedded template
material for the 16 NCERT books (see `_NCERT_BOOKS` in `seed.py`) that
ship with no real uploaded PDF (`file_url is None`). Mirrors the two
examples (Class 4 EVS/Math) that already existed in `seed.py` before this
file: original, curriculum-aligned prose written to match each book's real
NCERT chapter list and the `Topic` taxonomy in `curriculum_seed.py` — not
scanned/copied textbook text.

Each entry is chunked+embedded once via `chunk_service.ingest_module_text`
and stored as `DocumentChunk` rows tagged with `ncert_book_id`. Two things
read this real content instead of the one-line "Chapter 1: Overview"
fallback once it exists:
  - `module_service.add_ncert_module`: copies these template chunks into a
    school's own branch when the school adds this NCERT book to a class.
  - `scripts/generate_questions.py`: RAG-grounds the generic quiz-question
    generator in this content via `chunk_service.search_chunks_for_rag`.

Keyed by (subject, class_number). Extend/correct here directly, same
review-friendly spirit as `curriculum_seed.py` — an error here is a text
edit, not a prompt-engineering problem.
"""

NCERT_CHAPTER_TEXT: dict[tuple[str, int], str] = {
    # ── EVS ──────────────────────────────────────────────────────────────────
    ("EVS", 3): (
        "Chapter 1: My Family\n"
        "A family is a group of people who live together and take care of "
        "each other. Some families are small, with just parents and one or "
        "two children. Some families are large, with grandparents, uncles, "
        "aunts, and cousins living together or nearby. Every member of a "
        "family has a relationship to every other member — a mother's "
        "brother is a maama or uncle, a father's mother is a grandmother. "
        "Families help each other, share meals, and celebrate festivals "
        "together. No two families are exactly alike, and that is normal.\n\n"
        "Chapter 2: Keeping My Body Healthy\n"
        "Our body has many parts that each do an important job — eyes to "
        "see, ears to hear, hands to hold, and legs to walk and run. To "
        "keep the body healthy, we must bathe daily, brush our teeth twice "
        "a day, wash our hands before eating and after using the toilet, "
        "and wear clean clothes. Eating a mix of vegetables, fruits, grains, "
        "and milk keeps us strong. Playing outside and sleeping enough "
        "hours every night also keeps the body and mind healthy.\n\n"
        "Chapter 3: Plants Around Us\n"
        "Plants can be as small as grass or as tall as a banyan tree. A "
        "plant usually has roots, a stem, leaves, and sometimes flowers and "
        "fruits. Roots hold the plant in the soil and take in water. Herbs "
        "are short and soft-stemmed, like coriander. Shrubs are medium-"
        "sized with many woody stems, like a rose bush. Trees are tall with "
        "one thick, hard, woody stem, like a mango tree. Plants give us "
        "food, shade, wood, and the oxygen we breathe.\n\n"
        "Chapter 4: Water, Water Everywhere\n"
        "Water comes from many sources: rivers, lakes, wells, ponds, rain, "
        "and underground borewells. People use water for drinking, "
        "cooking, bathing, washing clothes, and watering crops. Not all "
        "water is safe to drink — river and well water is usually boiled "
        "or filtered first. Water should never be wasted, because some "
        "villages and towns do not have enough of it. Simple habits like "
        "turning off the tap while brushing teeth help save water."
    ),
    ("EVS", 4): (
        "Chapter 1: Going to School\n"
        "Children use different ways to reach school in different parts of India. "
        "In Assam, children cross bamboo and rope bridges to reach school when it rains heavily. "
        "In Ladakh, children use a trolley attached to a strong iron rope over a wide and deep river to cross over. "
        "In Kerala, children use a Vallam (a small wooden boat) to reach school. "
        "In Rajasthan desert, children ride in camel carts over hot sand. "
        "In plains, children ride bullock carts or bicycles through green fields.\n\n"
        "Chapter 2: Ear to Ear\n"
        "Different animals have different types of ears. Animals like elephants, rabbits, dogs, and tigers have ears that can be seen. "
        "Birds, frogs, lizards, and snakes have ears, but they are tiny holes covered with feathers or skin. "
        "Animals whose ears can be seen and have hair on their skin give birth to young ones (Viviparous). "
        "Animals whose ears cannot be seen and do not have hair on their skin lay eggs (Oviparous).\n\n"
        "Chapter 3: A Day with Nandu\n"
        "Nandu is a three-month-old baby elephant. Elephants live in herds. "
        "An elephant herd has mainly females and baby elephants. The oldest female elephant is the leader of the herd. "
        "Adult elephants eat more than 100 kilograms of leaves and twigs in one day. "
        "Elephants sleep for only 2 to 4 hours a day. They love to play in mud and water to keep their skin cool.\n\n"
        "Chapter 4: The Story of Amrita\n"
        "Amrita lived in Khejadli village near Jodhpur in Rajasthan. The village got its name from the many Khejadi trees that grew there. "
        "The people of Khejadli were called Bishnois. They cared deeply for plants and animals, saying 'Agar ped hain to hum hain'. "
        "When the King sent soldiers to cut trees to build his palace, Amrita and her three daughters hugged the trees to protect them. "
        "Over 300 villagers sacrificed their lives protecting the Khejadi trees."
    ),
    ("EVS", 5): (
        "Chapter 1: Inside My Body\n"
        "Our body works because several systems work together. The "
        "digestive system breaks down the food we eat, starting in the "
        "mouth and ending in the intestines, so our body can use it for "
        "energy. The respiratory system, using the nose, windpipe, and "
        "lungs, brings in oxygen and removes carbon dioxide every time we "
        "breathe. The circulatory system, powered by the heart, pumps "
        "blood through blood vessels to carry oxygen and nutrients to "
        "every part of the body. These systems work every second, even "
        "while we sleep.\n\n"
        "Chapter 2: Our Natural Resources\n"
        "Natural resources are things from nature that people use, like "
        "water, soil, forests, coal, and sunlight. Renewable resources, "
        "such as sunlight, wind, and water, can be used again and again "
        "and do not run out easily. Non-renewable resources, such as coal "
        "and petroleum, take millions of years to form and will eventually "
        "run out if overused. Conservation means using resources wisely — "
        "planting trees, saving water, using solar energy, and reducing "
        "waste so resources last for future generations too.\n\n"
        "Chapter 3: Staying Safe in a Disaster\n"
        "A natural disaster is a sudden event caused by nature, such as an "
        "earthquake, flood, cyclone, or fire, that can harm people and "
        "property. During an earthquake, it is safest to take cover under "
        "sturdy furniture and stay away from windows. During a flood, "
        "people should move to higher ground and avoid walking through "
        "moving water. Keeping a small emergency kit with a torch, water, "
        "and important documents, and knowing your local emergency "
        "numbers, helps a family stay safe.\n\n"
        "Chapter 4: How Our Community Is Run\n"
        "A community is a group of people living in the same area, like a "
        "village or a town. Local governance is how that community makes "
        "decisions together. In villages, a Gram Panchayat, led by an "
        "elected Sarpanch, looks after roads, water supply, schools, and "
        "cleanliness. In cities, a Municipal Corporation does similar "
        "work. Citizens can vote to choose their local leaders and can "
        "raise problems, like a broken street light or dirty drain, with "
        "these local bodies."
    ),
    # ── Mathematics ──────────────────────────────────────────────────────────
    ("Mathematics", 1): (
        "Chapter 1: Counting to Twenty\n"
        "We count objects one by one, saying one number for each object: "
        "1, 2, 3, and so on, up to 20. Counting helps us know how many "
        "things there are — how many pencils in a box, or how many birds "
        "on a wire. Numbers can also be written using digits, like 7 or "
        "15. Practising counting forward (1, 2, 3...) and backward (20, "
        "19, 18...) helps build a strong sense of number order.\n\n"
        "Chapter 2: Which Is More?\n"
        "When we compare two groups of objects, one group can have more, "
        "fewer, or the same number as the other. We use the words "
        "'greater than', 'less than', and 'equal to' to compare numbers. "
        "For example, 8 is greater than 5, and 5 is less than 8. Lining "
        "up objects from two groups side by side, one to one, is an easy "
        "way for young children to see which group has more.\n\n"
        "Chapter 3: Joining and Taking Away\n"
        "Addition means joining two groups of things together to find the "
        "total, such as 4 apples plus 3 apples makes 7 apples. "
        "Subtraction means taking away some things from a group to find "
        "what is left, such as 9 balloons minus 2 balloons leaves 7 "
        "balloons. Both can be practised within numbers up to 20, using "
        "fingers, counters, or drawings to make the idea concrete.\n\n"
        "Chapter 4: Shapes Around Us\n"
        "Many everyday objects are shaped like simple 2D shapes. A ball "
        "is round like a circle. A book cover is shaped like a rectangle. "
        "A slice of pizza can look like a triangle. A window can be a "
        "square, which is a special rectangle with all four sides equal. "
        "Circles have no corners, while triangles have three corners and "
        "squares and rectangles have four."
    ),
    ("Mathematics", 2): (
        "Chapter 1: Tens and Ones\n"
        "Any 2-digit number is made up of tens and ones. The number 34 "
        "means 3 tens and 4 ones, because 3 tens (30) plus 4 ones (4) "
        "makes 34. Understanding place value this way makes it much "
        "easier to add and subtract larger numbers, because tens can be "
        "added to tens and ones to ones.\n\n"
        "Chapter 2: Adding with Carrying\n"
        "When we add two 2-digit numbers and the ones digits add up to 10 "
        "or more, we 'carry' 1 ten over to the tens column. For example, "
        "adding 27 and 15: 7 ones plus 5 ones makes 12, so we write 2 and "
        "carry 1 ten, then add that carried ten to 2 tens plus 1 ten to "
        "get 42. Practising with small objects grouped into tens makes "
        "carrying easier to picture.\n\n"
        "Chapter 3: Subtracting with Borrowing\n"
        "Sometimes the ones digit of the number being subtracted is "
        "bigger than the ones digit of the top number. Then we 'borrow' "
        "1 ten from the tens column and add it as 10 ones. For example, "
        "in 42 minus 15, since 2 is smaller than 5, we borrow a ten from "
        "the 4, making it 12 minus 5 in the ones place, and 3 tens minus "
        "1 ten in the tens place, giving 27.\n\n"
        "Chapter 4: What Is Multiplication?\n"
        "Multiplication is a quick way to add the same number many times. "
        "3 groups of 4 apples each is the same as 4 + 4 + 4, which is 12 "
        "apples, and can be written as 3 times 4 equals 12. Skip counting "
        "— counting in jumps of 2, 5, or 10 — is one of the easiest ways "
        "for a young learner to first discover multiplication."
    ),
    ("Mathematics", 3): (
        "Chapter 1: Learning Tables\n"
        "A multiplication table shows the results of multiplying a number "
        "by 1, 2, 3, and so on. Knowing the tables of 2 through 10 by "
        "heart makes many everyday calculations — like working out the "
        "cost of 6 notebooks at 8 rupees each — much faster. Tables also "
        "follow patterns: the table of 5 always ends in 0 or 5, and the "
        "table of 10 always ends in 0.\n\n"
        "Chapter 2: Sharing Equally\n"
        "Division means splitting a group of things into equal smaller "
        "groups. If 12 sweets are shared equally among 3 friends, each "
        "friend gets 4 sweets, because 12 divided by 3 is 4. Division is "
        "the opposite of multiplication — if 3 times 4 is 12, then 12 "
        "divided by 3 is 4, and 12 divided by 4 is 3.\n\n"
        "Chapter 3: Bigger Numbers\n"
        "A 3-digit number has hundreds, tens, and ones places. The number "
        "356 means 3 hundreds, 5 tens, and 6 ones. We can write this as "
        "300 + 50 + 6. Reading and building 3-digit numbers with place-"
        "value blocks (hundreds, tens, and ones blocks) helps make the "
        "size of these numbers easier to picture.\n\n"
        "Chapter 4: Halves and Quarters\n"
        "A fraction shows a part of a whole. If a roti is cut into 2 "
        "equal pieces, each piece is one-half, written as 1/2. If it is "
        "cut into 4 equal pieces, each piece is one-quarter, written as "
        "1/4. The bottom number of a fraction shows how many equal parts "
        "the whole was cut into, and the top number shows how many of "
        "those parts we are talking about.\n\n"
        "Chapter 5: Measuring Things\n"
        "We measure length in centimetres and metres, weight in grams "
        "and kilograms, capacity (how much liquid something holds) "
        "in millilitres and litres. A ruler measures the length of a "
        "pencil in centimetres. A weighing scale measures how heavy a bag "
        "of rice is in kilograms. Using the same standard units lets "
        "everyone compare measurements fairly."
    ),
    ("Mathematics", 4): (
        "Chapter 1: Building with Bricks\n"
        "Bricks have 6 faces, 12 edges, and 8 corners. Masons in Murshidabad built beautiful brick floor patterns for Jagriti School. "
        "Arches and brick patterns can be seen in old bridges and kilns. "
        "A brick kiln bakes thousands of raw clay bricks. One brick usually measures 20 cm by 10 cm by 10 cm.\n\n"
        "Chapter 2: Long and Short\n"
        "Distance is measured in millimeters, centimeters, meters, and kilometers. 100 centimeters equals 1 meter, and 1000 meters equals 1 kilometer. "
        "Marathon races are about 40 kilometers long. Height is measured using a measuring tape. "
        "Comparing heights of classmates helps understand difference in length.\n\n"
        "Chapter 3: A Trip to Bhopal\n"
        "Class 4 students went on a school trip to Bhopal. Each mini bus held 35 children. "
        "They crossed the Narmada bridge which is 756.8 meters long. "
        "At Bhimbetka, they saw 10,000-year-old cave paintings of wild bulls, rhinos, and deer drawn on cave walls.\n\n"
        "Chapter 4: Tick-Tick-Tick\n"
        "Clocks show time in hours, minutes, and seconds. A clock face has 12 numbers and 60 small minute divisions. "
        "The short hand is the hour hand, and the long hand is the minute hand. 60 minutes make 1 hour, and 24 hours make 1 day. "
        "Reading 12-hour and 24-hour clocks helps plan daily routines and train timetables."
    ),
    ("Mathematics", 5): (
        "Chapter 1: Fractions With Different Bottoms\n"
        "To add or subtract fractions that have different denominators "
        "(bottom numbers), like 1/2 and 1/3, we first find a common "
        "denominator that both bottom numbers can divide into evenly — "
        "here, 6. Then 1/2 becomes 3/6 and 1/3 becomes 2/6, so 1/2 + 1/3 "
        "= 3/6 + 2/6 = 5/6. Comparing fractions works the same way: "
        "converting them to a common denominator first.\n\n"
        "Chapter 2: Working with Decimals\n"
        "A decimal number, like 4.7, has a whole-number part and a "
        "fractional part separated by a decimal point. To add or "
        "subtract decimals, we line up the decimal points and then add "
        "or subtract as usual: 4.7 + 2.3 = 7.0. To multiply decimals, we "
        "multiply the numbers as if there were no decimal point, then "
        "place the decimal point in the answer by counting the total "
        "decimal places in both numbers being multiplied.\n\n"
        "Chapter 3: Understanding Percent\n"
        "Percent means 'out of a hundred'. 25 percent, written 25%, means "
        "25 out of every 100, which is the same as the fraction 25/100 or "
        "the decimal 0.25. If 40 out of 100 students in a school like "
        "cricket, that is 40% of students. Percentages are used often in "
        "real life, like discounts in a shop or marks scored in an exam.\n\n"
        "Chapter 4: Area and Volume\n"
        "The area of a shape is the amount of flat surface it covers, "
        "measured in square units, such as square centimetres. A "
        "composite shape is made of two or more simple shapes joined "
        "together, and its area is found by adding the areas of its "
        "parts. Volume is how much space a solid object takes up, "
        "measured in cubic units — the volume of a cuboid is found by "
        "multiplying its length, width, and height.\n\n"
        "Chapter 5: Dividing Big Numbers\n"
        "Long division also works for large dividends and 2-digit "
        "divisors, following the same repeated steps: divide, multiply, "
        "subtract, and bring down the next digit. For example, dividing "
        "1,344 by 24 is done digit group by digit group until every digit "
        "of the dividend has been brought down and the final quotient and "
        "remainder are found."
    ),
    # ── English (Marigold) ───────────────────────────────────────────────────
    ("English", 1): (
        "Chapter 1: The Sounds of Letters\n"
        "Every letter of the alphabet has its own sound. The letter 'c' "
        "sounds like /k/ in 'cat', and the letter 'b' sounds like /b/ in "
        "'ball'. Learning these letter sounds, and blending them, is the "
        "first step to reading words like 'cat', 'bat', and 'hat'. "
        "Rhyming words, like 'cat' and 'hat', share the same ending "
        "sound and help children notice sound patterns in words.\n\n"
        "Chapter 2: Naming Things Around Me\n"
        "A noun is a word that names a person, animal, place, or thing, "
        "such as 'boy', 'dog', 'school', or 'ball'. Learning the names of "
        "everyday objects, family members, animals, and colours builds a "
        "strong basic vocabulary. A short story called 'A Happy Child' "
        "teaches simple words about a child's daily life: home, school, "
        "friends, and play.\n\n"
        "Chapter 3: Ten Little Fingers\n"
        "This chapter is a simple poem about counting fingers and toes, "
        "using short, easy sentences like 'I have ten little fingers' and "
        "'They all belong to me.' Reading such short, repeated sentences "
        "helps young readers recognise whole sentences, not just single "
        "words, and understand simple ideas written on the page.\n\n"
        "Chapter 4: What I Do Every Day\n"
        "This chapter introduces simple present tense sentences that "
        "describe daily actions, such as 'I wake up.', 'I brush my "
        "teeth.', and 'I go to school.' Nouns like 'sun', 'bed', and "
        "'bag' are combined with simple present-tense verbs to build "
        "complete, easy sentences a beginner reader can understand "
        "without help."
    ),
    ("English", 2): (
        "Chapter 1: Blending Sounds into Words\n"
        "By Class 2, children combine known letter sounds to read new, "
        "slightly longer words, like blending /s/, /t/, /o/, /p/ to read "
        "'stop'. Practising with word families that share an ending "
        "sound, like 'cat', 'mat', 'sat', and 'rat', builds reading "
        "speed and confidence with unfamiliar words.\n\n"
        "Chapter 2: Words That Describe\n"
        "Beyond naming things, we also use words that describe them — "
        "describing words like 'big', 'small', 'red', and 'soft' tell us "
        "more about a noun. A story called 'I Am Lucky' introduces "
        "descriptive vocabulary about a lucky boy's day, mixing everyday "
        "nouns with describing words in simple sentences.\n\n"
        "Chapter 3: A Short Story to Read\n"
        "This chapter has a short passage, 'Rain', about a rainy day, "
        "followed by simple questions like 'What did the boy see?' and "
        "'Where did he play?' Reading comprehension means being able to "
        "read a passage and correctly answer simple questions about what "
        "happened in it.\n\n"
        "Chapter 4: I, You, He, She\n"
        "A pronoun takes the place of a noun so we don't repeat the same "
        "name again and again — 'I', 'you', 'he', 'she', 'it', and "
        "'they' are pronouns. Combined with the simple present tense "
        "('He plays.', 'She reads.'), pronouns let us talk about people "
        "and things without always saying their full name.\n\n"
        "Chapter 5: Making Full Sentences\n"
        "A complete simple sentence has a naming part (who or what) and "
        "a telling part (what they do), such as 'The dog runs.' or 'Mia "
        "sings a song.' Practising joining a noun or pronoun with a "
        "matching action word builds the habit of writing full, correct "
        "sentences instead of single words."
    ),
    ("English", 3): (
        "Chapter 1: Words That Mean the Same\n"
        "Some different words can mean almost the same thing, like "
        "'happy' and 'glad', or 'big' and 'large'. Learning such word "
        "meanings, and simple synonyms, helps a young reader understand "
        "unfamiliar words in a passage by connecting them to words they "
        "already know.\n\n"
        "Chapter 2: The Tiger and the Woodpecker\n"
        "This chapter tells a short story about a tiger stuck with a "
        "bone caught in its teeth, and a small woodpecker who bravely "
        "helps pull it out. After reading, children answer questions "
        "like 'Who helped the tiger?' and 'Why was the tiger stuck?', "
        "practising story comprehension.\n\n"
        "Chapter 3: Yesterday and Today\n"
        "The simple past tense describes actions that already happened, "
        "such as 'walked', 'played', or 'jumped' — usually formed by "
        "adding '-ed' to the action word. Combined with pronouns, we get "
        "sentences like 'She played in the park yesterday.' or 'They "
        "walked to school.'\n\n"
        "Chapter 4: Describing People and Places\n"
        "A descriptive sentence paints a clear picture using detail "
        "words, such as 'The tall, green tree stood near the old red "
        "house.' Practising describing a person's appearance, a place's "
        "look, or a thing's colour and size builds richer sentence "
        "writing beyond simple naming."
    ),
    ("English", 4): (
        "Chapter 1: Opposites and Same Meanings\n"
        "A synonym is a word with a similar meaning to another word "
        "(like 'big' and 'huge'), while an antonym is a word with the "
        "opposite meaning (like 'big' and 'small'). Recognising synonyms "
        "and antonyms in a passage helps a reader understand shades of "
        "meaning and builds a richer vocabulary for writing.\n\n"
        "Chapter 2: Wake Up Story\n"
        "This chapter is a longer passage about a boy who dreams of "
        "different animals waking up in the morning — a cat stretching, "
        "a rooster crowing, a cow mooing. Longer passages have more "
        "detail and more than one event, so questions ask children to "
        "recall the order of events, not just a single fact.\n\n"
        "Chapter 3: Tomorrow's Plans\n"
        "The simple future tense describes actions that have not "
        "happened yet, using 'will', such as 'I will visit my "
        "grandmother tomorrow.' Adjectives — describing words like "
        "'tall', 'kind', and 'colourful' — are placed before a noun to "
        "add detail: 'a kind grandmother', 'a colourful kite.'\n\n"
        "Chapter 4: Joining Ideas Together\n"
        "Two short sentences can be joined into one using a joining "
        "word (conjunction) like 'and', 'but', or 'because'. For "
        "example, 'I like mangoes. I like bananas.' becomes 'I like "
        "mangoes and bananas.' Joining sentences this way makes writing "
        "flow better and avoids short, choppy sentences."
    ),
    ("English", 5): (
        "Chapter 1: Guessing Meaning from Context\n"
        "Sometimes we don't know a word, but we can guess its meaning "
        "from the words and sentences around it — this is understanding "
        "meaning from context. For example, in 'The parched land had not "
        "seen rain for months', the word 'parched' can be guessed to "
        "mean very dry, because of the rest of the sentence.\n\n"
        "Chapter 2: Ice-Cream Man\n"
        "This chapter is a poem about a cheerful man who sells ice cream "
        "in the neighbourhood. After reading, children practise making "
        "simple inferences — for example, guessing that children are "
        "happy to see him because of how the poem describes them running "
        "towards his bicycle, even though the poem never says the word "
        "'happy' directly.\n\n"
        "Chapter 3: Mixing Past, Present, and Future\n"
        "A single passage can use different tenses together to describe "
        "what already happened, what is happening now, and what will "
        "happen — for example, 'She finished her homework, is watching "
        "TV now, and will sleep soon.' Conjunctions like 'and', 'but', "
        "'so', and 'because' connect these ideas smoothly.\n\n"
        "Chapter 4: Sentences with More Than One Idea\n"
        "A complex sentence joins a main idea with an extra clause using "
        "words like 'because', 'although', or 'when' — for example, "
        "'She was late because the bus broke down.' Complex sentences "
        "let a writer explain reasons, conditions, or timing, instead of "
        "only stating separate simple facts."
    ),
    # ── Hindi (Rimjhim) — content in Hindi, matching the Hindi topic set ────────
    ("Hindi", 1): (
        "Chapter 1: वर्णों की पहचान\n"
        "हिंदी वर्णमाला में स्वर और व्यंजन होते हैं। हर वर्ण की अपनी एक ध्वनि "
        "होती है, जैसे 'क' से 'कमल' और 'म' से 'मछली'। वर्णों को पहचानना और "
        "उनकी ध्वनि बोलना पढ़ने की पहली सीढ़ी है। सरल शब्दों में वर्णों को जोड़"
        "कर पढ़ने का अभ्यास बच्चों को नए शब्द पढ़ने में मदद करता है।\n\n"
        "Chapter 2: मेरे आसपास की चीज़ें\n"
        "संज्ञा वह शब्द है जो किसी व्यक्ति, जानवर, जगह या वस्तु का नाम बताता "
        "है, जैसे 'लड़का', 'कुत्ता', 'स्कूल', या 'गेंद'। रोज़मर्रा की चीज़ों, "
        "परिवार के सदस्यों, जानवरों और रंगों के नाम सीखना मूल शब्दावली बनाने "
        "में सहायक है।\n\n"
        "Chapter 3: छोटे-छोटे वाक्य\n"
        "यह पाठ सरल वाक्यों से भरा है, जैसे 'यह मेरी गुड़िया है।' और 'मुझे "
        "आम पसंद है।' छोटे और दोहराए गए वाक्य पढ़ने से बच्चे पूरे वाक्य को "
        "समझना सीखते हैं, न कि केवल अलग-अलग शब्दों को।\n\n"
        "Chapter 4: मैं रोज़ क्या करता हूँ\n"
        "इस पाठ में वर्तमान काल के सरल वाक्य हैं, जैसे 'मैं उठता हूँ।', 'मैं "
        "स्कूल जाता हूँ।' संज्ञा शब्दों जैसे 'सूरज', 'बिस्तर', और 'बस्ता' को "
        "सरल वर्तमान काल की क्रियाओं के साथ जोड़कर आसान वाक्य बनाए गए हैं।"
    ),
    ("Hindi", 2): (
        "Chapter 1: शब्द बनाना सीखना\n"
        "कक्षा 2 में बच्चे जाने-पहचाने वर्णों की ध्वनियों को जोड़कर थोड़े "
        "बड़े शब्द पढ़ना सीखते हैं। एक जैसी अंतिम ध्वनि वाले शब्दों के "
        "समूह, जैसे 'नल', 'जल', 'फल', का अभ्यास करने से नए शब्द पढ़ने की "
        "गति और आत्मविश्वास बढ़ता है।\n\n"
        "Chapter 2: नई शब्दावली\n"
        "नाम बताने वाले शब्दों के साथ-साथ हम गुणवाचक शब्दों का भी प्रयोग "
        "करते हैं, जैसे 'बड़ा', 'छोटा', 'लाल', और 'मुलायम'। ये शब्द किसी "
        "वस्तु के बारे में अधिक जानकारी देते हैं और वाक्यों को रोचक बनाते "
        "हैं।\n\n"
        "Chapter 3: एक छोटी कहानी\n"
        "इस पाठ में 'बारिश' नाम का एक छोटा अनुच्छेद है, जिसके बाद सरल "
        "प्रश्न पूछे गए हैं, जैसे 'बच्चे ने क्या देखा?' गद्यांश बोध का "
        "अर्थ है किसी अनुच्छेद को पढ़कर उसके बारे में सरल प्रश्नों के सही "
        "उत्तर दे पाना।\n\n"
        "Chapter 4: मैं, तुम, वह\n"
        "सर्वनाम वह शब्द है जो संज्ञा के स्थान पर प्रयोग होता है, जैसे "
        "'मैं', 'तुम', 'वह', और 'वे'। सर्वनाम को वर्तमान काल की क्रिया के "
        "साथ जोड़कर हम बिना नाम दोहराए किसी के बारे में बात कर सकते हैं, "
        "जैसे 'वह खेलता है।'\n\n"
        "Chapter 5: पूरा वाक्य बनाना\n"
        "एक पूर्ण सरल वाक्य में कर्ता (कौन) और क्रिया (क्या करता है) दोनों "
        "होते हैं, जैसे 'कुत्ता दौड़ता है।' या 'मीरा गीत गाती है।' संज्ञा "
        "या सर्वनाम को सही क्रिया के साथ जोड़ने का अभ्यास सही वाक्य लिखने "
        "की आदत बनाता है।"
    ),
    ("Hindi", 3): (
        "Chapter 1: एक जैसे अर्थ वाले शब्द\n"
        "कुछ अलग-अलग शब्दों का अर्थ लगभग एक जैसा होता है, जैसे 'खुश' और "
        "'प्रसन्न', या 'बड़ा' और 'विशाल'। ऐसे पर्यायवाची शब्दों को सीखने "
        "से बच्चे किसी अनजान शब्द को पहचाने हुए शब्द से जोड़कर समझ पाते "
        "हैं।\n\n"
        "Chapter 2: बहादुर बच्चा\n"
        "इस पाठ में एक बहादुर बच्चे की कहानी है जिसने मुसीबत में फँसे अपने "
        "दोस्त की मदद की। कहानी पढ़ने के बाद बच्चों से पूछा जाता है 'किसने "
        "मदद की?' और 'दोस्त मुसीबत में कैसे फँसा?', जिससे कहानी की समझ "
        "जाँची जाती है।\n\n"
        "Chapter 3: कल और आज\n"
        "भूतकाल उन कामों के बारे में बताता है जो पहले हो चुके हैं, जैसे "
        "'खेला', 'गया', या 'देखा'। सर्वनाम के साथ जोड़कर हमें वाक्य मिलते "
        "हैं जैसे 'वह कल पार्क में खेला।' या 'वे स्कूल गए।'\n\n"
        "Chapter 4: लोगों और जगहों का वर्णन\n"
        "वर्णनात्मक वाक्य विवरण देने वाले शब्दों से एक स्पष्ट चित्र बनाता "
        "है, जैसे 'ऊँचा, हरा पेड़ पुराने लाल घर के पास खड़ा था।' किसी "
        "व्यक्ति के रूप-रंग, किसी जगह के दृश्य, या किसी वस्तु के रंग और "
        "आकार का वर्णन करने का अभ्यास वाक्य लेखन को समृद्ध बनाता है।"
    ),
    ("Hindi", 4): (
        "Chapter 1: विलोम और पर्यायवाची शब्द\n"
        "पर्यायवाची शब्द किसी शब्द के समान अर्थ वाला शब्द होता है (जैसे "
        "'बड़ा' और 'विशाल'), जबकि विलोम शब्द उसके विपरीत अर्थ वाला शब्द "
        "होता है (जैसे 'बड़ा' और 'छोटा')। किसी अनुच्छेद में पर्यायवाची और "
        "विलोम शब्दों को पहचानना शब्दावली को समृद्ध बनाता है।\n\n"
        "Chapter 2: सवेरे की कहानी\n"
        "इस पाठ में एक बड़ा अनुच्छेद है जिसमें सुबह अलग-अलग जानवरों के "
        "जागने का वर्णन है — बिल्ली अंगड़ाई लेती है, मुर्गा बांग देता है, "
        "गाय रंभाती है। बड़े अनुच्छेदों में कई घटनाएँ होती हैं, इसलिए "
        "प्रश्नों में घटनाओं का सही क्रम याद करना पूछा जाता है।\n\n"
        "Chapter 3: कल की योजना\n"
        "भविष्य काल उन कामों के बारे में बताता है जो अभी नहीं हुए हैं, "
        "जैसे 'मैं कल दादी से मिलूँगा।' विशेषण — जैसे 'ऊँचा', 'दयालु', और "
        "'रंग-बिरंगा' — संज्ञा से पहले लगाकर वाक्य में और जानकारी जोड़ते "
        "हैं, जैसे 'दयालु दादी', 'रंग-बिरंगी पतंग'।\n\n"
        "Chapter 4: वाक्यों को जोड़ना\n"
        "दो छोटे वाक्यों को संयोजक शब्द जैसे 'और', 'लेकिन', या 'क्योंकि' "
        "से जोड़कर एक वाक्य बनाया जा सकता है। जैसे 'मुझे आम पसंद हैं। मुझे "
        "केले पसंद हैं।' को जोड़कर 'मुझे आम और केले पसंद हैं।' बनता है। "
        "इससे लेखन सहज और प्रवाहमय बनता है।"
    ),
    ("Hindi", 5): (
        "Chapter 1: प्रसंग से अर्थ समझना\n"
        "कभी-कभी हमें कोई शब्द नहीं पता होता, लेकिन हम उसके आसपास के "
        "वाक्यों से उसका अर्थ अनुमान लगा सकते हैं — इसे प्रसंग से अर्थ "
        "समझना कहते हैं। जैसे 'सूखी धरती पर महीनों से बारिश नहीं हुई थी', "
        "इस वाक्य से 'सूखी' का अर्थ समझा जा सकता है, भले ही शब्द पहले न "
        "पढ़ा हो।\n\n"
        "Chapter 2: बर्फ वाला दादा\n"
        "यह एक कविता है जो मोहल्ले में आइसक्रीम बेचने वाले एक खुशमिजाज़ "
        "व्यक्ति के बारे में है। पढ़ने के बाद बच्चे अनुमान लगाने का अभ्यास "
        "करते हैं — जैसे यह समझना कि बच्चे उसे देखकर खुश हैं, भले ही "
        "कविता में सीधे 'खुश' शब्द न लिखा हो।\n\n"
        "Chapter 3: भूत, वर्तमान और भविष्य साथ-साथ\n"
        "एक ही अनुच्छेद में अलग-अलग काल एक साथ प्रयोग हो सकते हैं, जैसे "
        "'उसने अपना काम खत्म किया, अभी टीवी देख रही है, और जल्दी सोएगी।' "
        "संयोजक शब्द जैसे 'और', 'लेकिन', 'इसलिए', और 'क्योंकि' इन विचारों "
        "को आपस में जोड़ते हैं।\n\n"
        "Chapter 4: एक से अधिक विचार वाले वाक्य\n"
        "जटिल वाक्य एक मुख्य विचार को अतिरिक्त उपवाक्य से जोड़ता है, जैसे "
        "'क्योंकि', 'हालांकि', या 'जब' शब्दों का प्रयोग करके — जैसे 'वह "
        "देर से आई क्योंकि बस खराब हो गई थी।' जटिल वाक्य लेखक को कारण, "
        "शर्त, या समय स्पष्ट करने में मदद करते हैं।"
    ),
}
